services:
  common_a:
    image: debian:12
    command: sleep infinity
    develop:
      watch:
        - action: sync
          path: ./src_com1
          target: /app


  common_b:
    image: debian:12
    command: sleep infinity
    develop:
      watch:
        - action: sync
          path: ./src_com2
          target: /app

