services:
  svr_f:
    image: debian:12
    command: sh -c "env | sort && sleep infinity"
    profiles:
      - p1
      - p1_3
    develop:
      watch:
        - action: sync
          path: $APP2_DIR/src5
          target: /app

  svr_g:
    image: debian:12
    command: sleep infinity
    profiles:
      - p2
    develop:
      watch:
        - action: sync
          path: $APP2_DIR/src6
          target: /app

